name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.16.x, 1.15.x, 1.14.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: make test
    - name: Test with GOARCH=386
      run: env GOARCH=386 make test
    - name: Test Coverage
      run: |
        go test -cover ./... | grep 100.0% || {
          go test -cover ./...
          echo Coverage decreased!
          exit 1
        } >&2
    - name: Lint
      run: make lint
